FROM apache/airflow:latest

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless \
    curl \
    procps \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/airflow/spark/jars

RUN curl -L -o /opt/airflow/spark/jars/mysql-connector-j-8.4.0.jar \
    https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.4.0/mysql-connector-j-8.4.0.jar

WORKDIR /opt/airflow

USER airflow

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

RUN pip install --no-cache-dir \
    "apache-airflow-providers-apache-spark" \
    "pyspark" \
    "openmeteo-requests" \
    "requests-cache" \
    "urllib3==1.26.18" \
    "pipdeptree" \
    "python-dotenv" \
    "yfinance"\
    "google-cloud-bigquery"\
    "google-auth-oauthlib" \
    "google-auth-httplib2" 
    # "torch" \
    # "transformers" \
    # "accelerate" \
    # "gluonts" \
    # "pandas-gbq" \
    # "matplotlib"